#ifndef STAVALFI_CPP_EX3_CONFIGURATION_TYPES_H
#define STAVALFI_CPP_EX3_CONFIGURATION_TYPES_H


enum class ConfigurationTypes {
    INITIAL_HEAP_SIZE,
    VALGRIND_ENABLED
};


#endif //STAVALFI_CPP_EX3_CONFIGURATION_TYPES_H
